name: VHDL Simulation

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar GHDL
        run: sudo apt-get install -y ghdl

      #IMPORTANTE: TROQUEM "meu_circuito.vhdl" PELO NOME DO ARQUIVO QUE VOCÊS VÃO COMPILAR (e do testebench tb também)!!!!
      - name: Analisar arquivos
        run: |
          ghdl -a src/soma.vhdl 
          ghdl -a tb/tb_soma.vhdl

      - name: Elaborar
        run: ghdl -e tb_soma

      - name: Simular
        run: ghdl -r tb_soma --vcd=waveform.vcd

      - name: Salvar waveform como artefato
        uses: actions/upload-artifact@v4
        with:
          name: waveform
          path: waveform.vcd