name: VHDL Simulation

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar GHDL
        run: sudo apt-get install -y ghdl

      - name: Listar arquivos
        run: |
          ls -la src/
          ls -la tb/
          
      - name: Analisar arquivos
        run: |
          ghdl -a --std=08 src/ula_pack.vhdl

          ghdl -a --std=08 src/mult_escalar.vhdl 
          ghdl -a --std=08 tb/tb_mult_escalar.vhdl

          ghdl -a --std=08 src/soma.vhdl 
          ghdl -a --std=08 tb/tb_soma.vhdl

          ghdl -a --std=08 src/subtracao.vhdl 
          ghdl -a --std=08 tb/tb_subtracao.vhdl

          ghdl -a --std=08 src/convolucao.vhdl
          ghdl -a --std=08 tb/tb_convolucao.vhdl

          ghdl -a --std=08 src/mux_2to1.vhdl
          ghdl -a --std=08 src/reg_signed.vhdl
          ghdl -a --std=08 src/multiplicacao.vhdl
          ghdl -a --std=08 tb/tb_multiplicacao.vhdl

          ghdl -a --std=08 src/banco_reg.vhdl
          ghdl -a --std=08 src/comparator.vhdl
          ghdl -a --std=08 src/unsigned_adder.vhdl
          ghdl -a --std=08 src/unsigned_register.vhdl
          ghdl -a --std=08 src/counter.vhdl
          ghdl -a --std=08 src/memoria.vhdl
          ghdl -a --std=08 src/mux_8to1.vhdl
          ghdl -a --std=08 src/reg.vhdl
          ghdl -a --std=08 src/signed_adder.vhdl
          ghdl -a --std=08 src/signed_register.vhdl
          ghdl -a --std=08 src/ula_bo.vhdl

          ghdl -a --std=08 tb/tb_bo.vhdl
          



      - name: Elaborar
        run: |
          ghdl -e --std=08 tb_mult_escalar
          ghdl -e --std=08 tb_soma
          ghdl -e --std=08 tb_subtracao
          ghdl -e --std=08 tb_convolucao
          ghdl -e --std=08 tb_multiplicacao
          ghdl -e --std=08 tb_bo

      - name: Simular
        run: |
          ghdl -r --std=08 tb_mult_escalar --vcd=waveform_mult_escalar.vcd
          ghdl -r --std=08 tb_soma --vcd=waveform_soma.vcd
          ghdl -r --std=08 tb_subtracao --vcd=waveform_subtracao.vcd
          ghdl -r --std=08 tb_convolucao --vcd=waveform_convolucao.vcd
          ghdl -r --std=08 tb_multiplicacao --vcd=waveform_multiplicacao.vcd
          ghdl -r --std=08 tb_bo --vcd=waveform_tb.vcd

      - name: Salvar waveforms como artefatos
        uses: actions/upload-artifact@v4
        with:
          name: waveforms
          path: "*.vcd"