name: VHDL Simulation

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar GHDL
        run: sudo apt-get install -y ghdl

      #IMPORTANTE: TROQUEM "meu_circuito.vhdl" PELO NOME DO ARQUIVO QUE VOCÊS VÃO COMPILAR (e do testebench tb também)!!!!
      - name: Listar arquivos
        run: |
          ls -la src/
          ls -la tb/
          
      - name: Analisar arquivos
        run: |
          ghdl -a src/ula_pack.vhdl

          ghdl -a src/mult_escalar.vhdl 
          ghdl -a tb/tb_mult_escalar.vhdl

          ghdl -a src/soma.vhdl 
          ghdl -a tb/tb_soma.vhdl

          ghdl -a src/subtracao.vhdl 
          ghdl -a tb/tb_subtracao.vhdl

          ghdl -a src/convolucao.vhdl
          ghdl -a tb/tb_convolucao.vhdl

          ghdl -a src/mux_2to1.vhdl
          ghdl -a src/reg_signed.vhdl
          ghdl -a src/multiplicacao.vhdl
          ghdl -a tb/tb_multiplicacao.vhdl

          ghdl -a src/ula.vhdl
          
          ghdl -a src/bc.vhdl
          ghdl -a tb/tb_bc.vhdl
          ghdl -a tb/tb_ula.vhdl

      - name: Elaborar
        run: |
         ghdl -e tb_mult_escalar
         ghdl -e tb_soma
         ghdl -e tb_subtracao
         ghdl -e tb_convolucao
         ghdl -e tb_multiplicacao
         ghdl -e tb_bc
         ghdl -e tb_ula

      - name: Simular
        run: |
         ghdl -r tb_mult_escalar --vcd=waveform.vcd
         ghdl -r tb_soma --vcd=waveform.vcd
         ghdl -r tb_subtracao --vcd=waveform.vcd
         ghdl -r tb_convolucao --vcd=waveform.vcd
         ghdl -r tb_multiplicacao --vcd=waveform.vcd
         ghdl -r tb_bc --vcd=waveform.vcd
         ghdl -r tb_ula --vcd=waveform.vcd

      - name: Salvar waveform como artefato
        uses: actions/upload-artifact@v4
        with:
          name: waveform
          path: waveform.vcd
